apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-tax-labels-ui
  namespace: ai-apps  # Adjust namespace as needed
spec:
  replicas: 1  # You can scale this as needed
  selector:
    matchLabels:
      app: ml-app-tax-labels-ui
  template:
    metadata:
      labels:
        app: ml-app-tax-labels-ui
    spec:
      containers:
      - name: ml-app-tax-labels-ui
        image: pdesaidocker/ml-classification-tax-labels-ui:{{imageTag}}
        resources:
          requests:
            memory: "128Mi"   # Minimum memory for the container to function
            cpu: "25m"       # Minimum CPU for the container to function
          limits:
            memory: "256Mi"   # Maximum memory that can be used
            cpu: "50m"       # Maximum CPU that can be used
        ports:
        - containerPort: 80
